### ISSUE TITLE
Websocket 'orders'

### ISSUE THREAD

**Issue by hans24o** [escwdev/kucoin-node-api#21]
Hey I think I found a bug,

when using the ws topic 'orders' I get an invalid topic error.
I could fix it by replacing '/market/level3:' with '/spotMarket/tradeOrders' in line 140 of the `lib/websockets.js` file.

Hope this helps.

**Comment by escwdev** [comment]
Yeah, this hasn't been updated to the most recent endpoint that Kucoin added. If you put in the commit I'll review and merge but I'll try to get to it this week if not anyway. Thanks.

**Comment by escwdev** [comment]
This is included in the new version.
