### ISSUE TITLE
What am I doing wrong? (spot limit order)

### ISSUE THREAD

**Issue by Argon007** [escwdev/kucoin-node-api#22]
Hi,

Fairly new to this and it seems i'm doing something wrong... 
I try to set a Limit order in BTC-USDT as a test but I get a "undefined" back as response.

This is the code i'm using:
`api.placeOrder({clientOid: "test", side: "buy", symbol: "BTC-USDT", type: "limit", price: "49500", size: "60"}).then((r) => {
    console.log(r.data)
  }).catch((e) => {
    console.log(e)
  })`

The only response I get is:
`undefined`

Can you give me a clue what i'm doing wrong?
Thanks!

**Comment by Argon007** [comment]
Great.... 1 minute after I created this post i found my error... size needs to be in BTC and not in USDT

so this one is working perfectly:
`api.placeOrder({clientOid: "test", side: "buy", symbol: "BTC-USDT", type: "limit", price: "49500", size: "0.0015"}).then((r) => { console.log(r.data) }).catch((e) => { console.log(e) })`

Sorry ! :)

**Comment by escwdev** [comment]
No worries, just glad to see people getting use out of it!

It is interesting that you were getting undefined back. I thought `r.data` would return the error message that Kucoin sends as part of the payload back with some information on the error (likely lacking balance related).

I am going to close the issue but adjusting for any changes to error handling (both API related issues and REST issues which are separate) may be something to look into. Generally I leave that to the end user but if insufficient information is provided and response that is something to look into.

Cheers.
