### ISSUE TITLE
getSymbols API not working with market parameter

### ISSUE THREAD

**Issue by hirenreshamwala** [escwdev/kucoin-node-api#23]
The query parameter is missing in the query string.

market.js line number 11 replace

From:
```
let endpoint = '/api/v1/symbols'
```

To:
```
let endpoint = `/api/v1/symbols?market=${market}`
```

I hope this will help.

**Comment by escwdev** [comment]
Thanks hirenreshamwala.

I've updated `getSymbols()` to take an optional param for the market. The way you have it above it doesn't work by default for `all` markets so the optional route allows for both returning `all` if no param is provided or the specific market if one is (i.e. `BTC`).
