### ISSUE TITLE
how to get Callback when websocket closed...

### ISSUE THREAD

**Issue by FahadAlbukhari** [escwdev/kucoin-node-api#27]
Hi,

how to get Callback when websocket is closed?

**Comment by escwdev** [comment]
Can you provide a bit more detail and/or code showing your issue?

When the socket closes, it should provide a message or error. You can build around that to do what you want (i.e. a reconnect on a improperly disconnected socket).

**Comment by Shadowstep33** [comment]
`initSocket` returns `() => ws.close` so this should be true:

```
const ws = kc.initSocket(...);
ws(); //closes connection
```

**Comment by valyok333** [comment]
@Shadowstep33 Hello, using 

` const ws = api.initSocket(
        { topic: 'ticker', symbols: [`BTC-USDT`] },
        (msg) => {
          let data = JSON.parse(msg);
          console.log(data);
          }`
          
Then calling "ws()" to close the stream I receive the error

`TypeError: ws is not a function`

Any idea why I'm getting this?

**Comment by Shadowstep33** [comment]
You know what, sorry @valyok333 I lied. It works for me because I patched my version locally https://github.com/escwdev/kucoin-node-api/pull/30/files

**Comment by valyok333** [comment]
@Shadowstep33  Ah, I see. I added `return () => ws.close();` as you did but here, but, oddly enough, am still unable to close my stream. Even with `ws.close()`.

**Comment by escwdev** [comment]
See my other comment in your issue. You can access the underlying websockets as part of the original kc/api object. @valyok333 in your case it would be:

`api.ws.ticker.close()`
