### ISSUE TITLE
Closing ws stream

### ISSUE THREAD

**Issue by valyok333** [escwdev/kucoin-node-api#31]
Hello, I already commented this in another issue but figured it'd be appropriate to create an issue of my own.

I'm opening a websocket with:

`const ws = api.initSocket( { topic: 'ticker', symbols: [BTC-USDT] }, (msg) => { let data = JSON.parse(msg); console.log(data); }`

Then calling:

`ws();`

 to close the stream I receive the error

`TypeError: ws is not a function`

Any idea why I'm getting this? Is this the correct way to close the ws?

**Comment by escwdev** [comment]
Try `ws.close()`

`ws` is not a function it is an object that represents the websocket connection. It has several method functions including close().

**Comment by valyok333** [comment]
@escwdev I'm seeming to have the same problem using `ws.close()`. I've tried also tried calling api.initSocket without assigning it to a const and then just calling close() and am getting the same thing.

**Comment by escwdev** [comment]
Ok, I hadn't used this in awhile so it took me a second to play around and recall exactly how it works.

In this case, the websocket 'ticker' is stored in the parent `api` object.

The `const ws` you define is a promise function that starts the websocket. To access the underlying socket you don't interact with it but rather with the `api` object.

This worked when I tested it:

`api.ws.ticker.close()`

The top level `api` object stores all the open websockets in `api.ws`. To access one in particular and use the related methods like `close`, you use the topic.

**Comment by valyok333** [comment]
@escwdev Awesome! This worked. Thank you!  Also, fixed my code :-)
