### ISSUE TITLE
Typescript Interfaces

### ISSUE THREAD

**Issue by jonathan-irvin** [escwdev/kucoin-node-api#36]
Would it be possible to add typescript interfaces to your package?  I'm using it and love it.  If you don't have the time or bandwidth, I have a fork and may do it, too, but if you can, that would make my life so much easier.

I really appreciate it!
-JI

**Comment by escwdev** [comment]
Unfortunately I won't be able to integrate typescript for this project. You're certainly welcome to do so and maintain a fork.

I've shifted most my internal production use to the Rust version of the library and I've also got other ongoing projects so I simply don't have the time or use case to justify it right now.

**Comment by jonathan-irvin** [comment]
I appreciate the reply! I just may do that and make it its own thing.  I just didn't want to step on your toes.

It's a solid library.  I will retract my PR and continue on working it to be Typescript separately.  

Good luck on your other projects and I'll keep an eye on changes here to fold them in if you make any.

Sincerely,
@jonathan-irvin

**Comment by plungarini-mayp** [comment]
> I appreciate the reply! I just may do that and make it its own thing. I just didn't want to step on your toes.
> 
> It's a solid library. I will retract my PR and continue on working it to be Typescript separately.
> 
> Good luck on your other projects and I'll keep an eye on changes here to fold them in if you make any.
> 
> Sincerely, @jonathan-irvin

Do you managed to insert Typescript interfaces?

**Comment by jonathan-irvin** [comment]
@plungarini-mayp I ended up going with something else.
