### ISSUE TITLE
Problem with "PRIVATE" endpoint

### ISSUE THREAD

**Issue by Neetoo** [escwdev/kucoin-node-api#38]
Hello !
I just created an API Key on my sub account in order to do some test with their API.
The problem is when I want to do :

`await api.getAccounts()`

I have this error :

`TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined`

I checked all parameters, my connection, API credentials... Nothing work.

Thanks in advance !

**Comment by Matthiaas** [comment]
How did you fix it?
