### ISSUE TITLE
Repeated method: getFullOrderBookAtomic

### ISSUE THREAD

**Issue by migueldelmazo** [escwdev/kucoin-node-api#7]
Thank you very much for developing this library.

I think there is a bug. The getFullOrderBook method is not available.

The getFullOrderBook method is not available. Instead there are two methods getFullOrderBookAtomic. I guess the first of the two (`/api/v2/market/orderbook/level2?Symbol = $ {symbol}`) should be called getFullOrderBook.

https://github.com/escwdev/kucoin-node-api/blob/master/lib/market.js#L96

Thank you.

**Comment by escwdev** [comment]
Yes, thank you for catching this. The latter one was added after the original release as another endpoint. Probably the result of copy/pasting a portion of the function. I'll try and update when I have the opportunity.

**Comment by escwdev** [comment]
Finally updated!
